# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import youtube_dl_tiny_grpc_pb2 as youtube__dl__tiny__grpc__pb2


class YoutubeDLStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractInfo = channel.unary_stream(
                '/YoutubeDL/ExtractInfo',
                request_serializer=youtube__dl__tiny__grpc__pb2.ExtractInfoRequest.SerializeToString,
                response_deserializer=youtube__dl__tiny__grpc__pb2.ExtractInfoResponse.FromString,
                )


class YoutubeDLServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExtractInfo(self, request, context):
        """Return a stream of ExtractInfoResponse with extracted videos.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YoutubeDLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractInfo': grpc.unary_stream_rpc_method_handler(
                    servicer.ExtractInfo,
                    request_deserializer=youtube__dl__tiny__grpc__pb2.ExtractInfoRequest.FromString,
                    response_serializer=youtube__dl__tiny__grpc__pb2.ExtractInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'YoutubeDL', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class YoutubeDL(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExtractInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/YoutubeDL/ExtractInfo',
            youtube__dl__tiny__grpc__pb2.ExtractInfoRequest.SerializeToString,
            youtube__dl__tiny__grpc__pb2.ExtractInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
