---
services:
  youtube_dl_tiny_grpc:
    build: .
    environment:
      - VERBOSE=true
      - DEBUG=true
      - PROMETHEUS_ENABLE=true
      - REDIS_ENABLE=true
      - REDIS_URI=redis://redis:6379
      - GRPC_PORT=50051
      - YOUTUBE_DL_MAX_WORKERS=2
    ports:
      - "50051:50051"
      - "8080:8080"
    links:
      - redis
  redis:
    image: redis
