
name: Build
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '5 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          make docker-test
  push:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: docker/login-action@v1
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          registry: ghcr.io
          username: $GITHUB_USER
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          make docker-push \
            DOCKER_EXTRA_ARGS="-v ${HOME}/.docker:/root/.docker"
